# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y npm
  displayName: 'install and update npm'

- script: |
    npm audit || true
  displayName: 'npm audit'

- script: |
   npm test || true
  displayName: 'npm test'

- script: |
    sonar-scanner ||true
  displayName: 'review code'

- script: |
    sudo npm install
    sudo npm run build
  displayName: 'npm build'  
  